<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <LangVersion>latest</LangVersion>

    <AssemblyName>Eduq.Helpers</AssemblyName>
    <RootNamespace>Eduq.Helpers</RootNamespace>

    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <IncludeRefAssemblies>true</IncludeRefAssemblies>

    <PackageId>Eduq.Helpers</PackageId>
    <Version>1.0.0</Version>
    <Authors>Eduq</Authors>
    <Company>Eduq</Company>
    <Description>Eduq helpers</Description>
    <PackageTags>datetime;time;utilities</PackageTags>
    <RepositoryType>git</RepositoryType>

    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(IntermediateOutputPath)ref\\$(AssemblyName).dll')">
    <None Include="$(IntermediateOutputPath)ref\$(AssemblyName).dll" Pack="true" PackagePath="ref/$(TargetFramework)/" Visible="false" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(IntermediateOutputPath)ref\\$(TargetFramework)\\$(AssemblyName).dll')">
    <None Include="$(IntermediateOutputPath)ref\$(TargetFramework)\$(AssemblyName).dll" Pack="true" PackagePath="ref/$(TargetFramework)/" Visible="false" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(BaseIntermediateOutputPath)$(Configuration)\\$(TargetFramework)\\ref\\$(AssemblyName).dll')">
    <None Include="$(BaseIntermediateOutputPath)$(Configuration)\$(TargetFramework)\ref\$(AssemblyName).dll" Pack="true" PackagePath="ref/$(TargetFramework)/" Visible="false" />
  </ItemGroup>

</Project>
